version: 2
updates:
  - package-ecosystem: "npm"
    directory: "carpet-shopper/src/webui"
    schedule:
      interval: "daily"
    target-branch: wookie

  - package-ecosystem: "maven"
    directory: /
    schedule:
      interval: "daily"
    target-branch: wookie

  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "daily"
    target-branch: wookie
