version: 2
updates:
  - package-ecosystem: "npm"
    directory: "carpet-shopper/src/main/webui"
    schedule:
      interval: "daily"
    target-branch: wookie

  - package-ecosystem: "maven"
    directory: /
    schedule:
      interval: "daily"
    target-branch: wookie
    groups:
      quarkus-version:
        patterns:
          - "io.quarkus.platform:quarkus-bom"
          - "io.quarkus.platform:quarkus-maven-plugin"
          - "io.quarkus:quarkus-bom"
          - "io.quarkus:quarkus-maven-plugin"
          - "io.quarkus:quarkus-extension-processor"
          - "io.quarkus:quarkus-extension-maven-plugin"

  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "daily"
    target-branch: wookie
