# To get started with Dependabot version updates, you'll need to specify which
# package ecosystems to update and where the package manifests are located.
# Please see the documentation for all configuration options:
# https://docs.github.com/github/administering-a-repository/configuration-options-for-dependency-updates

version: 2
updates:
  - package-ecosystem: "npm" # See documentation for possible values
    directory: "cold-person/src/main/webui" # Location of package manifests
    schedule:
      interval: "weekly"
  - package-ecosystem: "maven" # See documentation for possible values
    directory: "cold-person" # Location of package manifests
    schedule:
      interval: "weekly"
  - package-ecosystem: "maven" # See documentation for possible values
    directory: "knitter" # Location of package manifests
    schedule:
      interval: "weekly"
  - package-ecosystem: "maven" # See documentation for possible values
    directory: "farmer" # Location of package manifests
    schedule:
      interval: "weekly"
  - package-ecosystem: "maven" # See documentation for possible values
    directory: "architecture-recorder" # Location of package manifests
    schedule:
      interval: "weekly"
  - package-ecosystem: "maven" # See documentation for possible values
    directory: "observer-extension" # Location of package manifests
    schedule:
      interval: "weekly"
  - package-ecosystem: "github-actions"
    # Workflow files stored in the
    # default location of `.github/workflows`
    directory: "/"
    schedule:
      interval: "weekly"
  - package-ecosystem: "npm" # See documentation for possible values
    directory: "carpet-shopper/src/main/webui" # Location of package manifests
    target-branch: wookie
    schedule:
      interval: "daily"
  - package-ecosystem: "maven" # See documentation for possible values
    directory: "carpet-shopper" # Location of package manifests
    target-branch: wookie
    schedule:
      interval: "daily"
  - package-ecosystem: "maven" # See documentation for possible values
    directory: "knitter" # Location of package manifests
    target-branch: wookie
    schedule:
      interval: "daily"
  - package-ecosystem: "maven" # See documentation for possible values
    directory: "wookie-tamer" # Location of package manifests
    target-branch: wookie
    schedule:
      interval: "daily"
  - package-ecosystem: "maven" # See documentation for possible values
    directory: "architecture-recorder" # Location of package manifests
    target-branch: wookie
    schedule:
      interval: "daily"
  - package-ecosystem: "maven" # See documentation for possible values
    directory: "observer-extension" # Location of package manifests
    target-branch: wookie
    schedule:
      interval: "daily"
  - package-ecosystem: "github-actions"
    # Workflow files stored in the
    # default location of `.github/workflows`
    directory: "/"
    target-branch: wookie
    schedule:
      interval: "daily"
